const assert = require('node:assert')
const BinarySearchTree = require('../../../Data Structures/binary-search-tree')
const checkSubTree = require('./practice')
const test = require('node:test')

test('checkSubTree - sub-tree', () => {
  const tree1 = new BinarySearchTree()
  tree1.insert(8)
  tree1.insert(4)
  tree1.insert(12)
  tree1.insert(5)
  tree1.insert(3)
  tree1.insert(15)
  tree1.insert(11)
  const tree2 = new BinarySearchTree(tree1.find(4))
  const output = checkSubTree(tree1.root, tree2.root)
  assert.deepEqual(output, true)
})

test('checkSubTree - not a sub-tree', () => {
  const tree1 = new BinarySearchTree()
  tree1.insert(8)
  tree1.insert(4)
  tree1.insert(12)
  tree1.insert(5)
  tree1.insert(3)
  tree1.insert(15)
  tree1.insert(11)
  const tree2 = new BinarySearchTree()
  tree2.insert(4)
  tree2.insert(2)
  tree2.insert(5)
  const output = checkSubTree(tree1.root, tree2.root)
  assert.deepEqual(output, false)
})