const assert = require('node:assert')
const StackOfPlates = require('./practice')
const test = require('node:test')

test(`stackMin`, () => {
  const stack = new StackOfPlates(3)
  const isEmpty1 = stack.isEmpty()
  stack.push(1)
  stack.push(2)
  stack.push(3)
  const isEmpty2 = stack.isEmpty()
  const peek1 = stack.peek()
  const numPlates1 = stack.numPlates()
  stack.push(4)
  const peek2 = stack.peek()
  const numPlates2 = stack.numPlates()
  stack.push(5)
  stack.push(6)
  const peek3 = stack.peek()
  const numPlates4 = stack.numPlates()
  stack.push(7)
  const peek4 = stack.peek()
  const numPlates5 = stack.numPlates()
  const pop = stack.pop(7)
  const peek5 = stack.peek()
  const numPlates6 = stack.numPlates()
  assert.deepEqual(isEmpty1, true)
  assert.deepEqual(isEmpty2, false)
  assert.deepEqual(peek1, 3)
  assert.deepEqual(numPlates1, 1)
  assert.deepEqual(peek2, 4)
  assert.deepEqual(numPlates2, 2)
  assert.deepEqual(peek3, 6)
  assert.deepEqual(numPlates4, 2)
  assert.deepEqual(peek4, 7)
  assert.deepEqual(numPlates5, 3)
  assert.deepEqual(pop, 7)
  assert.deepEqual(peek5, 6)
  assert.deepEqual(numPlates6, 2)
})
