const assert = require('node:assert')
const BinarySearchTree = require('../../../Data Structures/binary-search-tree')
const BinaryTree = require('../../../Data Structures/binary-tree')
const validateBST = require('./practice')
const test = require('node:test')

test('listOfDepths - valid BST', () => {
  const tree = new BinarySearchTree()
  tree.insert(1)
  tree.insert(3)
  tree.insert(2)
  tree.insert(9)
  tree.insert(7)
  const output = validateBST(tree.root)
  assert.deepEqual(output, true)
})

test('listOfDepths - invalid BST', () => {
  const tree = new BinaryTree()
  tree.insert(9)
  tree.insert(3)
  tree.insert(4)
  tree.insert(7)
  tree.insert(1)
  const output = validateBST(tree.root)
  assert.deepEqual(output, false)
})