const assert = require('node:assert')
const MinStack = require('./practice')
const test = require('node:test')

test(`stackMin`, () => {
  const stack = new MinStack([])
  const isEmpty1 = stack.isEmpty()
  stack.push(3)
  const isEmpty2 = stack.isEmpty()
  const min1 = stack.min()
  const peek1 = stack.peek()
  stack.push(4)
  const min2 = stack.min()
  const peek2 = stack.peek()
  stack.push(1)
  const min3 = stack.min()
  const pop1 = stack.pop()
  const min4 = stack.min()
  const pop2 = stack.pop()
  const min5 = stack.min()
  const pop3 = stack.pop()
  const isEmpty3 = stack.isEmpty()
  assert.deepEqual(isEmpty1, true)
  assert.deepEqual(isEmpty2, false)
  assert.deepEqual(min1, 3)
  assert.deepEqual(peek1, 3)
  assert.deepEqual(min2, 3)
  assert.deepEqual(peek2, 4)
  assert.deepEqual(min3, 1)
  assert.deepEqual(pop1, 1)
  assert.deepEqual(min4, 3)
  assert.deepEqual(pop2, 4)
  assert.deepEqual(min5, 3)
  assert.deepEqual(pop3, 3)
  assert.deepEqual(isEmpty3, true)
})